columnSuffix: null
contentColumnType: string
fieldGroup: d940a8f6-053a-45a4-b81c-3542dabfb242 # Common
handle: contentBlocks
instructions: null
name: 'Content blocks'
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentblocks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
