columnSuffix: null
contentColumnType: string
handle: contentBlocks
instructions: null
name: 'Content blocks'
searchable: false
settings:
  entryTypes:
    - 076b0212-b196-4ea1-b460-045d9ec97d53
    - a4cfb988-7ac8-4030-9aa8-2347b8717d78
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
