columnSuffix: hlgmabau
handle: text
instructions: null
name: 'Content blocks - Text - Text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: e957b4c1-4949-47dc-a211-74425267316e # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
