defaultPlacement: end
enableVersioning: true
entryTypes:
  - 468eac22-05c9-4b41-a09f-49966a6e217f # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primær artikkel-side'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  81f0c7e0-e850-4d6e-a6a5-4b8747a3f8cc: # Algorithms
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
