defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  81f0c7e0-e850-4d6e-a6a5-4b8747a3f8cc: # Algorithms
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
